# Project information
site_name: CameraScan
site_url: https://jenly1314.github.io/CameraScan/
site_description: "CameraScan for Android"
site_author: Jenly
remote_branch: gh-pages
edit_uri: ""

# Repository
repo_name: CameraScan
repo_url: https://github.com/jenly1314/CameraScan

# Copyright
copyright: 'Copyright &copy; 2024 Jenly.'

# Configuration
theme:
  name: 'material'
  icon:
    logo: material/github
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: octicons/sun-24
        name: "切换到深色模式"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: octicons/moon-24
        name: "切换到浅色模式"
  features:
    - navigation.tabs

markdown_extensions:
  - smarty
  - footnotes
  - meta
  - toc:
      permalink: true
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - tables

# Plugins
plugins:
  - search

nav:
  - '概览': index.md
  - 'API文档': api/index.html
  - '版本记录': changelog.md

