version: 2.1

orbs:
  android: circleci/android@3.0.0

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.08

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run: ./gradlew build
